<a href="https://colab.research.google.com/github/pavankumarb26/ML-Concepts/blob/main/Label_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Label Encoding

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

Label Encoding of Breast Cancer Dataset

In [ ]:
cancer_data = pd.read_csv("/content/data.csv")

In [ ]:
cancer_data.head()

Finding the count of different labels

In [ ]:
cancer_data["diagnosis"].value_counts()

load the label encoder function

In [ ]:
label_encoder = LabelEncoder()

In [ ]:
labels = label_encoder.fit_transform(cancer_data.diagnosis)

Appending the labels to the dataframe

In [ ]:
cancer_data["target"] = labels

In [ ]:
cancer_data.head()

In [ ]:
cancer_data["target"].value_counts()

In [10]:
iris_data = pd.read_csv("/content/iris_data.csv")

In [11]:
iris_data.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [13]:
iris_data['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [14]:
label_encoder_i = LabelEncoder()

iris_labels = label_encoder_i.fit_transform(iris_data.Species)

In [15]:
iris_data["target"] = iris_labels

In [16]:
iris_data.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,target
0,1,5.1,3.5,1.4,0.2,Iris-setosa,0
1,2,4.9,3.0,1.4,0.2,Iris-setosa,0
2,3,4.7,3.2,1.3,0.2,Iris-setosa,0
3,4,4.6,3.1,1.5,0.2,Iris-setosa,0
4,5,5.0,3.6,1.4,0.2,Iris-setosa,0

In [17]:
iris_data['target'].value_counts()

target
0    50
1    50
2    50
Name: count, dtype: int64